export const ERROR_MESSAGE_UPDATED = 'ERROR_MESSAGE_UPDATED'
export const INFO_MESSAGE_UPDATED = 'INFO_MESSAGE_UPDATED'
export const UPDATE_OWNERS_LIST = 'UPDATE_OWNERS_LIST'
export const UPDATE_LOGGED_WALLET = 'UPDATE_LOGGED_WALLET'
